apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: onprem-zta
spec:
  selector:
    app: service-a
  ports:
    - name: http
      port: 8000        # Service 對外 port
      targetPort: 8000  # 對應 containerPort（FastAPI 在 8000）
