apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: onprem-zta
spec:
  selector:
    app: service-b
  ports:
    - name: http
      port: 8001        # Service 對外 port
      targetPort: 8001  # 對應 containerPort（service-b 在 8001）
