apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: a-gw
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts: ["*"]
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: a-vs
  namespace: default
spec:
  hosts: ["*"]
  gateways: ["a-gw"]
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: service-a
        port:
          number: 8080
