apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: service-a } }
  template:
    metadata: { labels: { app: service-a } }
    spec:
      serviceAccountName: service-a
      containers:
      - name: app
        image: asia-east1-docker.pkg.dev/zero-trust-demo-475103/gcp-app/service-a:1.0
        env:
        - name: SERVICE_B_HOST
          value: "service-b.default.svc.cluster.local"
        - name: SERVICE_B_PORT
          value: "8080"
        ports: [{ containerPort: 8080 }]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: default
spec:
  selector: { app: service-a }
  ports: [{ port: 8080, targetPort: 8080 }]
