version: "3.9"

services:
  service-a:
    build:
      context: ./service-a
    container_name: onprem-service-a
    ports:
      - "8000:8000"      # 對外只開 service-a
    environment:
      - SERVICE_B_URL=http://service-b:8001
      - JWT_SECRET=supersecret
    depends_on:
      - service-b

  service-b:
    build:
      context: ./service-b
    container_name: onprem-service-b
    expose:
      - "8001"
    environment:
      - JWT_SECRET=supersecret
